Organizations:
  - &ExtraOrdererOrg
    # DefaultOrg defines the organization which is used in the sampleconfig
    # of the fabric.git development environment
    Name: ExtraOrdererOrg

    # ID to load the MSP definition as
    ID: ExtraOrdererOrgMSP

    MSPDir: ./organizations/ordererOrganizations/extra.com/msp

    # Policies defines the set of policies at this level of the config tree
    # For organization policies, their canonical path is usually
    #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ExtraOrdererOrgMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('ExtraOrdererOrgMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('ExtraOrdererOrgMSP.admin')"

    OrdererEndpoints:
      - orderer.extra.com:7050